name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 QEMU (关键步骤：为了支持在 GitHub 服务器上构建 ARM64/M2 镜像)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. 设置构建工具 Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. 登录 Docker Hub (需要去 GitHub Settings 配置 Secrets)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. 构建并推送 (多架构版)
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # 这是一个核心改动：同时构建 PC/服务器版(amd64) 和 M芯片版(arm64)
          platforms: linux/amd64,linux/arm64
          tags: |
            445022889/wuppp:latest
            445022889/wuppp:${{ github.sha }}
